//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonRehberi.Data.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int employeeID { get; set; }
        [Required(ErrorMessage ="Name field can't be null")]
        public string name { get; set; }
        [Required(ErrorMessage = "Surname field can't be null")]
        public string surname { get; set; }
        [Required(ErrorMessage = "Phone field can't be null")]
        public string phone { get; set; }
        public Nullable<int> departmentID { get; set; }
        public Nullable<int> managerID { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
